/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-background": "#2C2A28",
              "on-primary-fixed-variant": "#5A3A1A",
              "on-secondary-fixed": "#3A0000",
              "on-tertiary-fixed-variant": "#4c4733",
              "secondary-fixed": "#ffddd0",
              "primary-container": "#E8A56A",
              "on-surface": "#2C2A28",
              "surface-tint": "#D35400",
              "outline": "#8A7E74",
              "on-tertiary": "#ffffff",
              "error": "#ba1a1a",
              "on-primary-container": "#3A1E00",
              "outline-variant": "#C9BBB0",
              "primary-fixed": "#FFD9B3",
              "surface": "#FDF9F3",
              "on-secondary": "#ffffff",
              "secondary-container": "#D44A4A",
              "tertiary-fixed": "#ebe2c8",
              "primary-fixed-dim": "#E8A56A",
              "background": "#FDFBF7",
              "inverse-primary": "#E8A56A",
              "on-secondary-fixed-variant": "#5C0000",
              "on-tertiary-fixed": "#1f1c0b",
              "on-tertiary-container": "#fffbff",
              "tertiary": "#615c47",
              "secondary": "#8B0000",
              "on-error-container": "#93000a",
              "on-secondary-container": "#FFFFFF",
              "surface-container-lowest": "#FFFFFF",
              "on-primary": "#ffffff",
              "inverse-surface": "#33302e",
              "surface-container-low": "#FBF5ED",
              "on-primary-fixed": "#3A1E00",
              "surface-variant": "#EDE5DA",
              "on-surface-variant": "#5C5549",
              "on-error": "#ffffff",
              "primary": "#B35A28",
              "surface-container-highest": "#EDE5DA",
              "surface-container": "#F7F0E6",
              "surface-dim": "#E6DDD3",
              "secondary-fixed-dim": "#FF9E9E",
              "inverse-on-surface": "#f7efec",
              "surface-container-high": "#F1E9DF",
              "surface-bright": "#FDFBF7",
              "error-container": "#ffdad6",
              "tertiary-container": "#7b745e",
              "tertiary-fixed-dim": "#cec6ad",
              "gold": "#D4A843",
              "gold-light": "#FFD700",
              "warm-amber": "#F5C06A",
              "sunset-peach": "#F4A68C",
              "deep-rose": "#C75B6F",
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "sm": "1rem",
              "lg": "2.5rem",
              "xs": "0.5rem",
              "xl": "4rem",
              "gutter": "24px",
              "margin": "32px",
              "md": "1.5rem",
              "unit": "4px"
          },
          "fontFamily": {
              "body-lg": ["DM Sans", "sans-serif"],
              "label-md": ["DM Sans", "sans-serif"],
              "headline-md": ["Cormorant Garamond", "serif"],
              "headline-xl": ["Cormorant Garamond", "serif"],
              "headline-lg": ["Cormorant Garamond", "serif"],
              "body-sm": ["DM Sans", "sans-serif"],
              "quote": ["Cormorant Garamond", "serif"],
              "body-md": ["DM Sans", "sans-serif"]
          },
          "fontSize": {
              "body-lg": ["17px", { "lineHeight": "1.7", "fontWeight": "400" }],
              "label-md": ["11px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500" }],
              "headline-md": ["26px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "headline-xl": ["52px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "headline-lg": ["36px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "body-sm": ["13px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "quote": ["22px", { "lineHeight": "1.6", "fontStyle": "italic", "fontWeight": "400" }],
              "body-md": ["15px", { "lineHeight": "1.7", "fontWeight": "400" }]
          },
          "keyframes": {
              "float-dust": {
                  "0%, 100%": { transform: "translateY(0) translateX(0)", opacity: "0" },
                  "10%": { opacity: "0.25" },
                  "50%": { transform: "translateY(-60vh) translateX(30px)", opacity: "0.15" },
                  "90%": { opacity: "0.05" },
              },
              "shimmer": {
                  "0%": { backgroundPosition: "-200% 0" },
                  "100%": { backgroundPosition: "200% 0" },
              }
          },
          "animation": {
              "float-dust": "float-dust 18s ease-in-out infinite",
              "shimmer": "shimmer 3s ease-in-out infinite",
          }
      }
  },
  plugins: [],
}
